### ISSUE TITLE
"Weapon" in OnWar3EventPostHurt no longer returns correct item

### ISSUE THREAD

**Issue by RemyLebeau** [War3Source/War3Source#171]
Creating a new race, I was testing for specific weapons to deal bonus damage, and noticed it wasn't working.  Upon further testing I found that 

public OnWar3EventPostHurt(victim, attacker, Float:damage, const String:weapon[32], bool:isWarcraft)

The "weapon" string no longer returns the correct value.

For example,

I tried: 

PrintToChat(attacker, "Weapon is |%s|", weapon);

I then shot someone with an AK (or any other gun/knife for that matter), and it printed:

"Weapon is |player|"

As a further example, I modified the orc race to print the same debug statement, as can be seen on line 440 of the race, it expects the "weapon" value to return hegrenade.

When I through a grenade, it returns:

Weapon is |hegrenade_projectile|

I'm running MM 1.10.3, SM 1.6.1

**Comment by RemyLebeau** [comment]
Coming back to this now as it's been raised again by someone - DonRevan: surely that doesn't fix the root problem though?

If guns/knives are returning "player" (as described above), then that makes the function near useless.

**Comment by DonRevan** [comment]
Okay I gave it a shot, so the issue is that the game/sdkhooks never sends the weapon entity into our callback so our code uses the inflictor entity instead(which is either a grenade of the player itself).

I implemented some kind of translator that should fix existing plugins without a need to change anything to them.
Note: I'm not actually sure if this bug exists on CSGO(I'm pretty sure it does, just want to leave this here in case anybody experiences any problems :wink:)
