### ISSUE TITLE
war3source.cfg not being created

### ISSUE THREAD

**Issue by DraxB** [War3Source/War3Source#197]
Hi I was messing around with the war 3 source mod, and I found the wiki page which mentioned the war3source.cfg. However this config was never created when I launched my server. I only have the first 8 races, but other than that I have all the plugins for the mod. 

I'm currently using the latest version sourcemod: 1.7.3

My server also throws this message on launch: [War3Source] could not find war3source.cfg, we recommend all server this file

Any clues to what could be wrong? I'm not a developer so I can't do technical stuff but I did notice a commit to War3Source_Engine_Config.sp. I'm not sure if this commit has something to do with this, but any feedback would be nice.

**Comment by DonRevan** [comment]
That's not a bug, you've to create the file. It's simply a config file. Take a look at this:
http://war3source.com/index.php?topic=1923.0

**Comment by DraxB** [comment]
I see, but shouldn't the wiki page include all the CVARS then? I mean I already created one manually but I haven't found anywhere outside the link you just gave to all the CVARS :)

**Comment by DonRevan** [comment]
The problem is that the list has to be updated every time a developer adds or removes one. If we have a stable release sometime(who knows? :) there should be a comprehensive guide.
I totally forgot about the wiki, take a look at it too:
http://ownageclan.com/wiki/index.php/War3Source:Configuration

Most of the w3 cvars are automatically generated for each race/item.
